version: "3.9"

services:
  db:
     image: postgres:16
     container_name: postgres_c
     restart: always
     environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=host
      - POSTGRES_DB=postgres
     ports:
       - "5432:5432"
     volumes:
        - ./data:/var/lib/postgresql/data

  app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: fastapi
      restart: always
      ports:
          - "8033:8033"
      depends_on:
          - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db


networks:
  default:
    name: calendar