version: "3.9"

services:
  db:
     image: postgres:16
     container_name: db_server
     restart: always
     env_file:
       - .env
     ports:
       - "${DB_PORT}:${APP_PORT}"
     volumes:
        - ./data:/var/lib/postgresql/data

  app:
      command:
        bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8033"
      build:
        context: .
        dockerfile: Dockerfile
      container_name: fastapi
      env_file:
        - .env
      restart: always
      ports:
          - "${APP_PORT}:${APP_PORT}"
      depends_on:
          - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_CONTAINER_PORT}"
    depends_on:
      - db


networks:
  default:
    name: calendar