version: "3.9"

services:
  db:
     image: postgres:16
     container_name: postgres_c
     restart: always
     environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=host
      - POSTGRES_DB=postgres
     ports:
       - "5432:5432"
     volumes:
        - ./data:/var/lib/postgresql/data

  app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: fastapi
      restart: always
      ports:
          - "8033:8033"
      depends_on:
          - db
      volumes:
          - .:/app


networks:
  default:
    name: calendar