version: "3.9"

services:
  db:
     image: postgres:16
     container_name: db_server
     restart: always
     env_file:
       - .env
     ports:
       - "${DB_PORT}:5432"
     volumes:
        - ./data:/var/lib/postgresql/data

  app:
      build:
        context: .
        dockerfile: app/Dockerfile
      container_name: fastapi
      env_file:
        - .env
      restart: always
      ports:
          - "${APP_PORT}:8033"
      depends_on:
          - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db


networks:
  default:
    name: calendar