"""2_event_time

Revision ID: 141c3555c619
Revises: 5e80fd42117d
Create Date: 2023-12-15 10:59:32.427920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141c3555c619'
down_revision: Union[str, None] = '5e80fd42117d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('time', sa.TIME(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'time')
    # ### end Alembic commands ###
