"""22_11_23_10_01models

Revision ID: 3dabd8fc6c15
Revises: 05b5b695d2df
Create Date: 2023-11-22 07:01:47.686872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dabd8fc6c15'
down_revision: Union[str, None] = '05b5b695d2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
