"""4added_minor_additional_info

Revision ID: 8f7e1f09679c
Revises: ece5142f3668
Create Date: 2024-01-30 13:14:53.939069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7e1f09679c'
down_revision: Union[str, None] = 'ece5142f3668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('important_skip', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('events', 'name')
    op.drop_column('attendance', 'important_skip')
    # ### end Alembic commands ###
