"""5_event_date

Revision ID: 557d6528c1f7
Revises: 8f7e1f09679c
Create Date: 2024-01-31 09:18:23.772993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '557d6528c1f7'
down_revision: Union[str, None] = '8f7e1f09679c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('events', 'time',
               existing_type=postgresql.TIME(),
               type_=sa.TIME(timezone=True),
               existing_nullable=False)
    op.alter_column('notifications', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'creation_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('events', 'time',
               existing_type=sa.TIME(timezone=True),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.drop_column('events', 'date')
    # ### end Alembic commands ###
