"""21_11_23_18_01models

Revision ID: a7be3ad4a5db
Revises: fba6e519858d
Create Date: 2023-11-21 15:02:07.765321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7be3ad4a5db'
down_revision: Union[str, None] = 'fba6e519858d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
