"""21_11_23_18_32models

Revision ID: c15e1111d061
Revises: a7be3ad4a5db
Create Date: 2023-11-21 15:32:21.774958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15e1111d061'
down_revision: Union[str, None] = 'a7be3ad4a5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
